### ISSUE TITLE
Extras configuration clarification

### ISSUE THREAD

**Issue by d-tasevski** [gregorias/anki-code-highlighter#1]
So, after installing this add-on I'm stuck at this step:

> After fetching, run Extras > Configure Code Highlighter. This is necessary until Anki adds [addon lifecycle hooks](https://forums.ankiweb.net/t/install-update-delete-addon-hook-points/18532).

Can you clarify where the above command should be run? I don't have any "Extras" menu in my Anki application.

app info:

> Version ⁨2.1.49 (dc80804a)⁩
> Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

No other add-ons installed.

Thank you

**Comment by gregorias** [comment]
Hi [Darkø](https://github.com/d-tasevski),

You run this in Anki's GUI. "Extras" should be a menu option at the top. I'll add more clarification to the README shortly.

**Comment by gregorias** [comment]
I also have plans to automate this step.

**Comment by d-tasevski** [comment]
Interesting, I can see "Configure Code Highlighter" option in the Tools menu  on my Windows machine, but not on OSX. On OSX there is only "Delete ... " option:

<img width="284" alt="Screenshot 2022-04-03 at 13 34 48" src="https://user-images.githubusercontent.com/25148427/161425946-828b9485-9585-41b1-9cdf-67f2f71301fe.png">

Thanks for the clarification. I guess this is just FYI then, not working on Mac, and on Win, this option is inside the Tools menu, not Extras.

**Comment by gregorias** [comment]
Thanks for letting me know (I'm using a Linux version). I'll take a look. The good news is that you only need to run it on one machine.

**Comment by gregorias** [comment]
[I've reported the bug upstream](https://forums.ankiweb.net/t/cant-add-menu-entries-that-begin-with-config-on-macos/19201). I intend to change the name of the action to mitigate the issue.
