### ISSUE TITLE
Pressing the shortcut doesn’t trigger anything

### ISSUE THREAD

**Issue by arkhandir** [gregorias/anki-code-highlighter#16]
Hi, thank you for this plugin Grzegorz. 

On macOS 12.5.1 and Anki Version ⁨2.1.54 (b6a7760c)⁩ Python 3.9.7 Qt 6.3.1 PyQt 6.3.1, pressing the shortcut on selected code does nothing. I tried various other shortcuts without success. Any ideas? Thanks!

**Comment by gregorias** [comment]
Hi @arkhandir, could you try pressing `⌘+'`?

I forgot to update the instructions for macOS, where it's the command key not control.

**Comment by arkhandir** [comment]
Thanks! It works.

**Comment by arkhandir** [comment]
It worked for a short time, but soon I couldn't trigger anything with the shortcut again. I'm the last one to call for GUI elements, but in the current case I'm really at a loss as to how to use the add-on.

**Comment by gregorias** [comment]
I'll consider adding a GUI element soon

**Comment by gregorias** [comment]
I have a prerelease version that I need to test. If you want, you can try it out (attached), and let me know if it works for you.

[codehighlighter.zip](https://github.com/gregorias/anki-code-highlighter/files/9876122/codehighlighter.zip)

**Comment by gregorias** [comment]
I've pushed the newest version to Anki's repo.
