### ISSUE TITLE
Issue: IndexError:tuple index out of range

### ISSUE THREAD

**Issue by rc-bandit4461** [gregorias/anki-code-highlighter#20]
![image](https://user-images.githubusercontent.com/47919190/192891996-b1870cdb-4877-4444-bd3c-ff400ab6cf1e.png)
Just Installed the addon. Tried closing and reopening again, the issue persists

**Comment by gregorias** [comment]
Thank you for the report, @rc-bandit4461. I'll take look at it soon.

**Comment by gregorias** [comment]
The screenshot is not for my plugin but for https://ankiweb.net/shared/info/1463041493 (see the number). You can fetch my plugin at https://ankiweb.net/shared/info/112228974.
