### ISSUE TITLE
how to change the default justify-content:center to default left or justify?

### ISSUE THREAD

**Issue by Hosseingsd** [gregorias/anki-code-highlighter#30]
By default, the box will be placed centered, and every time I add a code, I have to justify it manually. Is there any way to change the default to left it justified?

![highlight code](https://user-images.githubusercontent.com/110593678/209968772-bcb2898a-ba5c-41d8-b28a-94e41213fb8a.png)

**Comment by gregorias** [comment]
There's no way to do this right now, but I intend to add a config option for that within a few days. Thanks for letting me know.

**Comment by gregorias** [comment]
In https://github.com/gregorias/anki-code-highlighter/commit/4c059021e428f87d3cf226674bb28cab3af17e3b, I've added `block-style` config option that should do what you want. Setting it to `"display: flex;" will left justify code blocks.

Feel free to reopen if that doesn't work for you.
