### ISSUE TITLE
C++ code block issue with new line in web editor in Desktop version (Pygments)

### ISSUE THREAD

**Issue by pedy** [gregorias/anki-code-highlighter#31]
As seen in the below image, when typing code in the web editor, hitting `Enter` or `Shift+Enter` would generate a `<br>` tag in the HTML source.
![0-RichEdit](https://user-images.githubusercontent.com/7770727/210516595-95feeead-c82f-4de1-aa48-d936f7dbd25e.png)
Applying Pygments C++ code *block* seems to be unable to replace `<br>` tags with new line.
![2](https://user-images.githubusercontent.com/7770727/210516631-9c1c08d7-b55f-4270-a83b-53d8f8164007.png)

Using HTML editor to type the code in would be inconvenient; for example because of `<` and `>` characters, that must be `&lt;` and `&gt; respectively.

**Comment by gregorias** [comment]
It's a valid bug, and I can reproduce it. I'll work on a fix. Thank you for reporting.
