### ISSUE TITLE
highlight.js for cloze cards?

### ISSUE THREAD

**Issue by pedy** [gregorias/anki-code-highlighter#32]
Is it impossible to support cloze cards with highlight.js, or it'd be a feature request?

To save time for possible further inquiries:
```html
Lambda Capture:<br><pre style="display:flex;"><code class="language-cpp">struct S2 { void f(int i); };
void S2::f(int i)
{
&nbsp;&nbsp;&nbsp; [&amp;]{};&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; // {{c1::OK: by-reference capture default}}
}</code></pre><br>
```
![image](https://user-images.githubusercontent.com/7770727/211759577-6db0c797-729e-4bfc-b67a-661b923149ea.png)
![image](https://user-images.githubusercontent.com/7770727/211759696-e77bb48e-8364-4aed-8b69-d8576a18da40.png)

**Comment by gregorias** [comment]
As far as I know, it's not possible, because you would need to change highlight.js to be aware of Anki-cloze mechanisms. That's why I added Pygments highlighting, to support Clozes.
