### ISSUE TITLE
line brakes disappear while pasting codes

### ISSUE THREAD

**Issue by Hosseingsd** [gregorias/anki-code-highlighter#43]
when i copy multiple lines of code and paste it to existing code box, all the line merge into just one long line and i have to delete all breaks and replace it with shift+enter key (using shift+enter is not big deal while typing codes from scratch but after pastin codes it's a tedious process).
how to prevent this in the first place?

![p1](https://user-images.githubusercontent.com/110593678/221529032-9264c389-1aa7-4eb9-a103-737bfcff69d3.jpg)

**Comment by gregorias** [comment]
Could you provide step by step instructions to reproduce what you mean?

**Comment by Hosseingsd** [comment]
![0](https://user-images.githubusercontent.com/110593678/222652339-2d76a146-d1d4-4c1a-ac2e-de6a9e5a571c.jpg)

![1](https://user-images.githubusercontent.com/110593678/222652327-6548dec2-74ec-44a7-aa6c-7c3fed81db8c.jpg)

![2](https://user-images.githubusercontent.com/110593678/222652317-f7235922-f2a5-4b9a-b9ac-8a59a3e98744.jpg)

![4](https://user-images.githubusercontent.com/110593678/222652302-1d9921a2-90d4-4c68-b399-56f9c3b102f2.jpg)

![5](https://user-images.githubusercontent.com/110593678/222652288-060a64a6-a25c-422d-804d-b151e45fce8f.jpg)

I want pasting in step 4 give me the desired result in the last image, automatically.

**Comment by gregorias** [comment]
You are pasting with HTML breaks (`<br>`), which get ignored by the highlighting mechanism. [This addon is only meant to highlight plaintext codeblocks.](https://github.com/gregorias/anki-code-highlighter#:~:text=the%20plugin%20works%20on%20untagged%20code%20blocks.%20do%20not%20add%20your%20own%20html%20tags%20like%20%3Ccode%3E%20or%20%3Cpre%3E%3Ccode%3E%20to%20the%20snippet%20you%20want%20to%20highlight.%20if%20you%20have%20run%20into%20issues%20with%20preannotated%20code%20snippets%2C%20see%20this%20comment%20for%20how%20to%20fix%20this.)

To address this, you should consider pasting unformatted text (e.g., CMD+SHIFT+V on macOS) or manipulating the HTML directly.

**Comment by Hosseingsd** [comment]
No there is no <br> in it.
Even if you paste in the notpad to stip any HTML formatting and then copy and paste in anki, the problem persist

**Comment by Hosseingsd** [comment]
No there is no br in it.
Even if you paste in the notpad to stip any HTML formatting and then copy and paste in anki, the problem persist

**Comment by gregorias** [comment]
Alright. Could you fill out a bug report and include the information it asks you for? Especially the field's HTML code.

**Comment by Hosseingsd** [comment]
> Alright. Could you fill out a bug report and include the information it asks you for? Especially the field's HTML code.

I don't familiar with GitHub process. (and I'm not a programmer). Do what you think is best.

**Comment by gregorias** [comment]
[Please fill out a bug report.](https://github.com/gregorias/anki-code-highlighter/issues/new?assignees=&labels=bug&template=bug_report.md&title=) The template will guide you to give us the information needed to debug this. It's especially important provide the HTML code of your fields.

**Comment by Hosseingsd** [comment]
I'm not a programmer but I'm learning. today I learned something about &lt;pre&gt; tag.
can't you implement this tag to solve this problem? It's just an idea and I don't know how! I'm an absolute beginner!

![code pre br](https://user-images.githubusercontent.com/110593678/229345605-dbef7c4e-e04f-4077-bb5c-e18ff62b3765.png)
