### ISSUE TITLE
Block code not indented

### ISSUE THREAD

**Issue by DallasBelt** [gregorias/anki-code-highlighter#44]
Hello dear developer! First of all, thanks a lot for your work on this addon.
The issue is that the code looks like this:

![image](https://user-images.githubusercontent.com/31676836/222836008-02b11f29-e910-401e-9c31-dcc60e39abe4.png)

I expected to see a proper indentation but it centers everything. If I try to use Pygments, it looks like this:

![image](https://user-images.githubusercontent.com/31676836/222836252-ccbaf43f-6e75-4f47-a3dc-dd0fbb799eef.png)

Perhaps I'm doing something wrong?

**Comment by gregorias** [comment]
Hi Diego,

There's probably something in your card setup that interferes with this addon's styling. In order for me to help you resolve this, [could you file a bug report](https://github.com/gregorias/anki-code-highlighter/issues/new?assignees=&labels=bug&template=bug_report.md&title=)? The template will guide you to give me the necessary information to debug this.

**Comment by DallasBelt** [comment]
I just filed the bug report, I hope it helps. Thank you!
