### ISSUE TITLE
Block code displays centered instead of aligned to the left and well indented

### ISSUE THREAD

**Issue by DallasBelt** [gregorias/anki-code-highlighter#45]
**Bug description**
When formatting a block code with highlight.js, it displays centered instead of aligned to the left and well indented. If I use Pygments, the result is shown with symbols (see screenshots).

**Reproduction steps**
1. Click on 'Add' in the main screen.
2. Write or paste the code in the field (if I paste from VSCode, I have to clean the HTML tags in the editor).
3. Select the text which I want to highlight.
4. Click on the addon icon or `Ctrl` + `'`
5. Select `highlight.js` and clock `OK`.
6. Select `HTML` (in my case) and click `OK`.
7. Click 'Add'.
8. Preview or review the card.

If applicable, provide the offending field's HTML code. For instructions how to get that code, see [this Anki help page](https://docs.ankiweb.net/editing.html#:~:text=button%20allows%20editing%20the%20underlying%20html).

**Expected behavior**
I expect that the block of code displays well indented and not centered.

**Screenshots**
If applicable, add screenshots to help explain your problem. You may mesh screenshots with reproduction steps instead of providing them in this separate section.

With highlight.js:
![image](https://user-images.githubusercontent.com/31676836/222919618-59c81f26-30ff-4270-8e6d-e4c48095585d.png)

With pygments:
![image](https://user-images.githubusercontent.com/31676836/222919686-e4145c53-8904-47bc-b6bb-0ed7a1093668.png)

**Card template**
If applicable, provide the card template code from the card that exhibits the unwanted behaviour. For instructions how to get that code, see [this Anki help page](https://docs.ankiweb.net/templates/intro.html#the-templates-screen).

Example Card HTML:
`{{c1::Test}}<pre style="display:block; justify-content:center;"><code class="language-html">&lt;head&gt;
&lt;meta&nbsp;charset="utf-8"&gt;
&lt;title&gt;Styles Conference&lt;/title&gt; &lt;link&nbsp;rel="stylesheet"&nbsp;href="assets/stylesheets/main.css"&gt;
&lt;/head&gt;</code></pre>`

Front Template:
`{{cloze:Text}}  <!-- Anki Code Highlighter (Addon 112228974) BEGIN --> <link rel="stylesheet" href="_ch-hljs-dracula.css" class="anki-code-highlighter"> <link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter"> <script src="_ch-my-highlight.js" class="anki-code-highlighter"></script> <!-- Anki Code Highlighter (Addon 112228974) END -->`

Back Template:
`{{cloze:Text}}<br> {{Back Extra}}  <!-- Anki Code Highlighter (Addon 112228974) BEGIN --> <link rel="stylesheet" href="_ch-hljs-dracula.css" class="anki-code-highlighter"> <link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter"> <script src="_ch-my-highlight.js" class="anki-code-highlighter"></script> <!-- Anki Code Highlighter (Addon 112228974) END -->`

Styling:
`.card {   font-family: arial;   font-size: 20px;   text-align: center;   color: black;   background-color: white; }  .cloze {  font-weight: bold;  color: blue; } .nightMode .cloze {  color: lightblue; }`

**Additional information**
 - OS version: Windows 11

**Additional context**
I haven't tuned the cards templates, but I'm using another addon that changes the interface a bit ([Advanced Review Bottom Bar](https://ankiweb.net/shared/info/1136455830)).

**Comment by gregorias** [comment]
Could you provide the field's HTML code and the card template code as instructed in the template?

**Comment by DallasBelt** [comment]
Sorry. I updated the comment including the needed information.

**Comment by gregorias** [comment]
![image](https://user-images.githubusercontent.com/722385/222920743-e74924ee-911c-4d40-8176-d6a27e3a67c4.png)

This highlighting is not from this plugin, which uses [solarized night](https://en.wikipedia.org/wiki/Solarized). What is this a picture of?

Here's how the rendered card looks like on my PC using the settings you have provided:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/722385/222920887-3eb455dc-c487-4e9e-a36b-d8dc2255d396.png">

Could you provide the following:
1. Screenshots of the editor window with the misbehaving card together with the HTML editor open.
2. Screenshots of the rendered card.
3. In reproduction steps, provide the text block you want me to copy to reproduce this.

Use [fenced code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) for pasting code with newlines.

You could also just try removing `text-align: center;` or changing it to `text-align: left` in your styling. Might help.

I suspect this `text-align: center` and not using unformatted pastes for copied HTML-trees from VS-code are the culprits.

**Comment by DallasBelt** [comment]
> What is this a picture of?
I used [your instructions](https://github.com/gregorias/anki-code-highlighter#custom-styles) to use custom styles. I'm using the Dracula theme, hence the different colors.

> Could you provide the following:
>     1. Screenshots of the editor window with the misbehaving card together with the HTML editor open.
Before applying syntax highlighting:
![image](https://user-images.githubusercontent.com/31676836/222924712-51b1cf30-7ae1-401b-9803-7ae77dd2ce13.png)

After applying syntax highlighting (highlight.js):
![image](https://user-images.githubusercontent.com/31676836/222924978-d75ea158-0a28-446f-bb84-aeeba2ccb0e1.png)

>     2. Screenshots of the rendered card.
![image](https://user-images.githubusercontent.com/31676836/222925015-6167d573-a4e6-4509-a00a-754d07e7cb32.png)

>     3. In reproduction steps, provide the text block you want me to copy to reproduce this.
I copied this from VSCode:
```
<head>
  <meta charset="utf-8">
  <title>Styles Conference</title>
  <link rel="stylesheet" href="assets/stylesheets/main.css">
</head>
```
> You could also just try removing text-align: center; or changing it to text-align: left in your styling. Might help.
That indeed aligns the block to the left but the indenting is missing (just like your screenshot).

> I suspect this `text-align: center` and not using unformatted pastes for copied HTML-trees from VS-code are the culprits.
Well, I used to copy from VSCode and paste (Ctrl + Shift + V) to Anki and it rendered ok, ie, with the `code` tag. Now, if I paste, the style is inherited from the default card, I guess. That's why I wrote that I had to remove some tags in the editor. This message appears if I don't do that:
![image](https://user-images.githubusercontent.com/31676836/222925553-18e526e1-89e7-4032-a983-a2314afa2e10.png)

**Comment by gregorias** [comment]
> That indeed aligns the block to the left but the indenting is missing (just like your screenshot).

<img width="697" alt="image" src="https://user-images.githubusercontent.com/722385/222925959-b71ee325-a07f-4b3e-8651-2ff9119902cd.png">

That are no indents in the HTML code itself, so it's hard to expect indents in the render. Once you add indenting whitespace, you should get your expected result.

**Comment by DallasBelt** [comment]
I'm dumb! Yes, I had to manually add the spaces. Sorry, I thought that the addon did the formatting stuff. But if I use pygments it shows the HTML entities instead of the symbols...

**Comment by gregorias** [comment]
You are right about the pygments thing. I'll take a look.
