### ISSUE TITLE
Anki freezes when highlighting code in cards using MathJax

### ISSUE THREAD

**Issue by pauldiloreto** [gregorias/anki-code-highlighter#48]
Hi! First off, just want to say thank you for an awesome Anki plugin. This is super helpful for a lot of CS-related studying.

**Bug description**
When syntax highlighting code, on some notes it causes Anki's browse window to become unresponsive. The main Anki window still works, but I am unable to close the browse window without force quitting Anki.
After reopening the card I was trying to add code highlighting to, I can see the selected text generated this code (which is incomplete compared to working code blocks I have in other Anki notes).

```
<span id="5115">text to highlight</span>
```
rather than:
```
<pre style="display:flex; justify-content:center;"><code class="language-typescript">text to highlight</code></pre>
```

**Reproduction steps**
1. Open the Anki browse window
2. Important: choose a card that is using MathJax (HTML outputs to `<anki-mathjax>text</anki-mathjax>`.
3. Highlight some additional plain text that is not MathJax.
5. Use the shortcut or click the button in the UI
6. After choosing highlight.js or pygments & the programming language, the edit portion of the Anki browse window becomes unresponsive & the window cannot be closed without force quitting.
7. Cancelling instead of applying the highlight also results in an unresponsive window.
8. Additional detail: Upon reopening, the addon no longer remembers what the previously used language was.

**Card template**
Not sure if this is relevant, but supplying in case it helps.

**Expected behavior**
Edit window should still be responsive and the correct HTML should be applied to the selected text.

**Card template**
My card template is pretty simple.
Front:
```
{{Front}}
```
Back:
```
{{FrontSide}}
<hr id=answer>
{{Back}}
```
Styling is also simple, so likely unrelated:
```
.card {
  font-family: arial;
  font-size: 20px;
}
```

**Additional information**
 - OS version: macOS Ventura 13.2.1
 - Apple M2 chip
 - Anki version:
   - Version ⁨2.1.60 (76d88073)⁩
   - Python 3.9.15 Qt 6.3.2 PyQt 6.3.1

**Comment by pauldiloreto** [comment]
Also just adding that this plugin works perfectly for me otherwise! If I remove all MathJax, apply the code highlighting, and then add the MathJax back in, everything works as expected.

Additionally, manually pasting the HTML around the text I'm trying to highlight works as well.

**Comment by gregorias** [comment]
Thank you for reporting. I'll take a look as soon as I have available time.

**Comment by gregorias** [comment]
Mhm, I can reproduce it, looking into the root cause.
