### ISSUE TITLE
Help with Anki

### ISSUE THREAD

**Issue by bananappleggplant** [gregorias/anki-code-highlighter#50]
Hello mr. milka

Good morning/afternoon/evening. (depending on what time you read)

Im not very good at programing.
I would like to use a shortcut for the "highlight text" button on anki (image below), since that on version 2.1.60 no feature as such exists.
I tried to use your add-on for that purpose (image below), but due to my lack of knowledge in programming i failed.

Is there a way to create a shortcut for it? Thanks for your time. 

=D
![image](https://user-images.githubusercontent.com/128747846/227350826-f3a274fd-7ef2-49ba-add4-e9bef03901aa.png)
![image](https://user-images.githubusercontent.com/128747846/227351040-a19441ed-9f83-4531-9918-842cd84db200.png)

**Comment by gregorias** [comment]
Do I understand correctly that you are looking for a keyboard shortcut? [The default shortcut is `CTRL-'`.](https://github.com/gregorias/anki-code-highlighter#:~:text=press%20ctrl%2B'%20(on%20macos%2C%20%E2%8C%98%2B')%20).
