### ISSUE TITLE
Request for Instructions on Customizing Pygments Styles

### ISSUE THREAD

**Issue by jesmarti** [gregorias/anki-code-highlighter#57]
Hi Grzegorz,

Thank you so much for creating this fantastic addon. It's an excellent tool that has aided my programming study sessions. I really appreciate your work on this!

I noticed in the readme, there are instructions on how to install custom styles for highlight.js, but not for Pygments due to its more complicated setup. I was wondering if there were any plans to add instructions for this in the future?

I eagerly awaiting this as I've found Pygments to work better with cloze and without the flickering issues that I've encountered with highlight.js.

Thanks again for your great work and I look forward to any updates you might have on this topic.

**Comment by gregorias** [comment]
Hi @jesmarti,

Thank you for your kind words.

Also thanks for reminding me about the issue. I would like to tackle this this summer but won't be able to do so within the next 2 weeks at least.

**Comment by jesmarti** [comment]
I appreciate your commitment to continue enhancing this already fantastic addon. I'll look forward to the upcoming improvements when you have the chance to implement them. Thanks again for all the work you do.

**Comment by gregorias** [comment]
I'm attaching a similar request from Lars as a reminder:

> Is it possible to change the highlighting style for inline code to be
“friendly_grayscale"?
>
> Styles — Pygments: https://pygments.org/styles/

**Comment by gregorias** [comment]
This is now done. For instructions, see https://github.com/gregorias/anki-code-highlighter#custom-styles.
