### ISSUE TITLE
Code-Highlighter not working. (https://github.com/RisingOrange/anki-enhanced-cloze got updated )

### ISSUE THREAD

**Issue by KAGEYAM4** [gregorias/anki-code-highlighter#64]
**Bug description**
https://github.com/RisingOrange/anki-enhanced-cloze got an update  and now code-highlighter is not displaying highlighted code.

**Reproduction steps**
1. Create a highligh-code using `ctrl-'`, `pygments`, `block`, `bash`.

If applicable, provide the offending field's HTML code.
```
Sometimes “silence is golden,” and we don't want output from a command, we just want to throw it away. This applies particularly to error and status messages. The system provides a way to do this by {{c1::redirecting output to a special file called “/dev/null”. This file is a system device often referred to as a <i>bit bucket</i>, which accepts input and does nothing with it}}. To suppress error messages from a command, we do this:<br><pre style="display:flex; justify-content:center;"><div class="pygments" style="display:flex; justify-content:center;">
<pre><code class="nohighlight"><span class="o">[</span>me@linuxbox<span class="w"> </span>~<span class="o">]</span>$<span class="w"> </span>ls<span class="w"> </span>-l<span class="w"> </span>/bin/usr<span class="w"> </span><span class="m">2</span>&gt;<span class="w"> </span>/dev/null
</code></pre>
</div>
</pre>
```

**Expected behavior**
The code isn't highlighted at all. Previously it was working fine.

**Screenshots**
![Screenshot_20230828_111631](https://github.com/gregorias/anki-code-highlighter/assets/75798544/fb563ad7-93b5-49f9-81b4-09d3daa3216c)

**Additional information**
 - OS version: [e.g. macOS 13.2.1]
 - OS: Arch Linux x86_64
 - Kernel: 6.4.12-arch1-1 
 - Anki 2.1.65 and Anki 2.1.66 ( Tested in both )

**Comment by gregorias** [comment]
Works fine on my side: 

<img width="731" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/722385/fb1b3649-c5da-4f00-910b-501a4503275d">

Could you provide your card template?

Could you try refreshing my plugin's assets? The menu option is under "Tools".

**Comment by KAGEYAM4** [comment]
`Refreshing` Code Assets worked. Thank you. 

You should add this troubleshooting tip to the Template of 	New Issue`.
