### ISSUE TITLE
Change font family

### ISSUE THREAD

**Issue by jesmarti** [gregorias/anki-code-highlighter#65]
Hello!
I was wondering if there is a way to change the font family of the code generated by the highlighter.
Also, thank you so much for creating this add-on.

**Comment by gregorias** [comment]
The plugin does not influence the font family of code blocks. It uses whatever comes with Anki. You may modify your stylesheet/Anki options to your own liking, e.g., https://tatsumoto-ren.github.io/blog/how-to-change-the-font-in-an-entire-anki-deck.html.

**Comment by jesmarti** [comment]
Thank you!
