### ISSUE TITLE
I can't set the default highlighter.

### ISSUE THREAD

**Issue by jesmarti** [gregorias/anki-code-highlighter#66]
**I can't set the default highlighter**
Setting a default highlighter causes the highlighter not to work at all.
I wonder if I'm doing anything wrong...

**Reproduction steps**
![image](https://github.com/gregorias/anki-code-highlighter/assets/122850714/8815bcf4-7e23-4177-99f8-60a224dc366f)
1. Add this line of code in the config window.
`"default-highlighter": "pygments"`

When saving changes and returning to the config page, the code is automatically reordered:
![image](https://github.com/gregorias/anki-code-highlighter/assets/122850714/7fd51121-7ca6-49ff-abc2-e018a6b58bee)

2. Refresh the assets.

**Expected behavior**
I expected the default highlighter's choice to appear as default.  However, when attempting to highlight code by using the shortcut or by clicking on the icon, the addon doesn't respond
![ezgif-5-cd1801d17a](https://github.com/gregorias/anki-code-highlighter/assets/122850714/7cf68752-1c10-4b77-89f5-1ab9e38b6dcc)

**Card Template**
Front:
```
{{Front}}

<!-- Anki Code Highlighter (Addon 112228974) BEGIN -->
<link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter">
<link rel="stylesheet" href="_ch-hljs-solarized.css" class="anki-code-highlighter">
<script src="_ch-highlight.js" class="anki-code-highlighter"></script>
<script src="_ch-my-highlight.js" class="anki-code-highlighter"></script>
<!-- Anki Code Highlighter (Addon 112228974) END -->
```

Back:
```
{{FrontSide}}

<hr id=answer>

{{Back}}

<!-- Anki Code Highlighter (Addon 112228974) BEGIN -->
<link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter">
<link rel="stylesheet" href="_ch-hljs-solarized.css" class="anki-code-highlighter">
<script src="_ch-highlight.js" class="anki-code-highlighter"></script>
<script src="_ch-my-highlight.js" class="anki-code-highlighter"></script>
<!-- Anki Code Highlighter (Addon 112228974) END -->
```

Styling:
```
.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
```

**Additional information**
 - OS version: Windows 10
 - Anki Version ⁨2.1.66 (70506aeb)⁩
- Python 3.9.15 Qt 6.5.2 PyQt 6.5.2

**Comment by gregorias** [comment]
Thank you for your detailed report. I can reproduce the issue and am taking a look.

**Comment by gregorias** [comment]
I found the issue, I should be able to fix it within 24h.
