### ISSUE TITLE
bug: Code Block - Selection Highlight Error

### ISSUE THREAD

**Issue by ht-l1** [gregorias/anki-code-highlighter#72]
**Bug description**
When I click on the add-on button trying to highlight the code block, it gives me the error below. 
"`The selection splits an HTML node, which prevents the highlighting plugin from proceeding`"

**Reproduction steps**
1. Go to 'card'
2. highlight the code block
3. Click on 'code highlight button'

If applicable, provide the offending field's HTML code. For instructions how to get that code, see [this Anki help page](https://docs.ankiweb.net/editing.html#:~:text=button%20allows%20editing%20the%20underlying%20html).

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. You may mesh screenshots with reproduction steps instead of providing them in this separate section.
<img width="429" alt="anki - code highlight error" src="https://github.com/gregorias/anki-code-highlighter/assets/106502799/0d4848bc-7964-4e93-9a9c-90fb5ccdcf38">

**Card template**
If applicable, provide the card template code from the card that exhibits the unwanted behaviour. For instructions how to get that code, see [this Anki help page](https://docs.ankiweb.net/templates/intro.html#the-templates-screen).

**Additional information**
 - OS version: [e.g. macOS 13.2.1]

**Additional context**

**Comment by gregorias** [comment]
Hi @ht-l1, thank you for raising this issue.

It's an unfortunate limitation of the way I managed to implement the main functionality of this plugin. I will not have the time to make the process more robust any time soon, but here are the steps needed to make it work for you:

1. [Check the HTML of the node](https://docs.ankiweb.net/editing.html#:~:text=the%20%3C%2F%3E%20button%20allows%20editing%20the%20underlying%20html%20of%20a%20field.%20). The code you select is probably wrapping with HTML elements and your selection is then probably selecting a partial HTML element.
2. Copy your code snippet into the HTML editor directly. This way you'll get rid of the offending HTML tags. Don't worry that the WYSWIG editor show the code snippet without any markup.
3. Select the code snippet in the WYSWIG editor and click highlight.

The above procedure should enable you to highlight your code snippets. In the future, I recommend either writing code snippets manually, pasting without markup (cmd+shift+v, I think) or pasting into the HTML editor to avoid running into this issue.

**Comment by ht-l1** [comment]
gotcha that makes perfect sense, thank you so much for providing the workarounds. 
Awesome plugin :) appreciate it @gregorias !
