### ISSUE TITLE
Highlight code from clipboard

### ISSUE THREAD

**Issue by BartoszPiwek** [gregorias/anki-code-highlighter#74]
[Previous used by me add-on](https://ankiweb.net/shared/info/1463041493) have it and I really miss it :)

**Comment by otrai** [comment]
Applying syntax highlighting from the clipboard saves time and makes it easier to create programming cards. Using a keyboard shortcut to paste and apply syntax highlighting simultaneously would be very useful.

Even though this is not an option, this is still a great tool for applying syntax highlighting. And you update it consistently - thank you.

**Comment by gregorias** [comment]
If such is the will of the people, I shall work on it.
