### ISSUE TITLE
Is there a way to have unhighlighted <pre><code> blocks?

### ISSUE THREAD

**Issue by revsuine** [gregorias/anki-code-highlighter#76]
Hiya,

Firstly thanks a ton for making this plugin; I've found it super useful for my Anki workflow.

I have a card with some pseudocode on it and I've put it in `<pre><code>` blocks. I think the plugin has automatically added highlighting that doesn't really make sense to the pseudocode. When I looked through the list of languages I didn't see a plaintext option.

Is it possible to add a plaintext/unhighlighted option for code blocks for pseudocode or anything else users might not want highlighted but still want to display in a code block? Or if this is something that is already possible I would appreciate being told how to do this :) Thanks!

**Comment by gregorias** [comment]
Thank you for your kind words and raising this to my attention.

highlight.js has plain text:

<img width="331" alt="grafik" src="https://github.com/gregorias/anki-code-highlighter/assets/722385/b7fd13f3-079b-4ba1-909d-a93cf1725333">

Does that work for you?

>  I think the plugin has automatically added highlighting that doesn't really make sense to the pseudocode.

That’s not good, I’ll take a look when I find some time.

**Comment by revsuine** [comment]
Thank you, I must have missed that! If it helps with the bug hunting, here is the exact html of the card in question:

```
<h1>
  Stack-based ISA
</h1><pre style="display:flex; justify-content:center;"><code>Push A
Push B
Add
Pop C</code></pre><h1>
  Accumulator-based ISA
</h1><pre style="display:flex; justify-content:center;"><code>Load A
Add B
Store C</code></pre><h1>
  Register-memory-based ISA</h1><pre style="display:flex; justify-content:center;"><code>Load R1, A
Add R3, R1, B
Store R3, C</code></pre><h1>Load-store-based ISA</h1><pre style="display:flex; justify-content:center;"><code>Load R1, A
Load R2, B
Add R3, R1, R2
Store R3, C</code></pre>
```

And the appearance:
![2024-01-17-113534_714x811_Screenshot](https://github.com/gregorias/anki-code-highlighter/assets/10424281/8d2f7911-9880-4d58-88d1-d02a890e1490)

**Comment by gregorias** [comment]
I found the culprint. [I’m calling `highlightAll`](https://github.com/gregorias/anki-code-highlighter/blob/cd7d0970de5a74ad5b7d2009e2902708f36e586c/assets/_ch-my-highlight.js#L1C1-L1C21), which highlights all `<pre><code>` tags. Will need to figure out a more targeted applications of hljs.
