### ISSUE TITLE
Add-on startup failed

### ISSUE THREAD

**Issue by mfscifly** [gregorias/anki-code-highlighter#78]
## Bug description

On Anki startup, add-on startup fails. Unable to create new cards using add-on features. Attempted add-on update however there are no new updates.

## Reproduction steps

Debug info from Anki:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1.2-arm64-arm-64bit

When loading Syntax Highlighting for Code:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/___/Library/Application Support/Anki2/addons21/1463041493/__init__.py", line 15, in <module>
    from . import main
  File "/Users/___/Library/Application Support/Anki2/addons21/1463041493/main.py", line 21, in <module>
    from .consts import *  # import addon_path
  File "/Users/___/Library/Application Support/Anki2/addons21/1463041493/consts.py", line 22, in <module>
    addon_path = os.path.dirname(__file__).decode(sys_encoding)
AttributeError: 'str' object has no attribute 'decode'

## Expected behavior

No error on startup. Should be able to continue to use code formatting when creating cards.

## Screenshots

<img width="513" alt="Screenshot 2024-03-05 at 10 35 36 AM" src="https://github.com/gregorias/anki-code-highlighter/assets/138173334/c10781e6-8947-47ba-bb2c-515cf9db150c">

## Card template

If applicable, provide the card template code from the card that exhibits the unwanted behaviour. For instructions how to get that code, see [this Anki help page](https://docs.ankiweb.net/templates/intro.html#the-templates-screen).

## Additional information

macOS 14.1.2

## Additional context

Other users have reported similar issues. Please see most recent reviews at: https://ankiweb.net/shared/info/1463041493

**Comment by gregorias** [comment]
Wrong plugin. The report is for [Syntax Highlighting for Code](https://ankiweb.net/shared/info/1463041493). My plugin is [Highlight Code](https://ankiweb.net/shared/info/112228974).

**Comment by mfscifly** [comment]
Wow, so sorry to bug you. How silly. I must have got them mixed up while trying to figure out what was wrong.

The good news is, using your plugin may solve the problem anyway.

Take care,

Daniel

**Comment by gregorias** [comment]
Sure. Let me know if you have any issues.
