### ISSUE TITLE
Automatically solve "selection splits an HTML node" situations

### ISSUE THREAD

**Issue by slnc** [gregorias/anki-code-highlighter#80]
When I select a snippet of text like in the following image, the highlighter complains that the selection splits an HTML node even though I selected complete lines 

<img width="907" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/69429/f598ceff-25b7-4d4f-b036-d672fab4eb9c">

Consider modifying the addon to navigate up the DOM tree to the nearest parent and automatically apply the style. It's less friction for the user and more consistent with how other text programs work (Google Docs, Apple Pages, etc).

This happens on:
**Anki**
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3

Current Code Highlighter plugin.

**Comment by gregorias** [comment]
That’s fair. I’m a little busy outside of this project right now though, so this will take time.

**Comment by gregorias** [comment]
Can you provide reproduction steps or does it happen with the same example as in the original message?
