### ISSUE TITLE
Remember my highlighter and language selections

### ISSUE THREAD

**Issue by slnc** [gregorias/anki-code-highlighter#81]
I normally create code snippets for the same language and I open and close Anki all the time. Right now the plugin asks me for a highlighter and a language for every card, and the language choice gets reset if I reopen Anki.

Consider adding a set of config options so that when I press the "Highlight current selection" toolbar button, it always uses the configured settings. E.g.:
- (checkbox) Always use this highlighter (menu to choose from `highlight.js` and `pygments`)
- (checkbox) Always use this language: (menu to choose the language)

If I activate any of those options and I want to change highlighter or language for a card, I will need to go to the addon's settings.

In the past couple of weeks alone I've created 120 code snippet cards. A feature like this would have saved me a lot of keypresses and context switches between focusing on the card contents and the mechanics of creating a card.

Thanks!

**Comment by gregorias** [comment]
I’ve implemented wizard state persistence, which should satisfy this feature request. Let me know if you have further comments.

**Comment by slnc** [comment]
Thanks Greg, it works great! I first tried to update the plugin via Anki's Tools > Add-ons > Check for Updates, but it didn't detect any updates. I guess it's a caching issue, but I mention it in case it's not that.
