### ISSUE TITLE
Add support for inline code highlighting

### ISSUE THREAD

**Issue by slnc** [gregorias/anki-code-highlighter#82]
If I use the plugin to prettify a card like this:

<img width="503" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/69429/1bfb9f40-5b15-4ac0-8632-3fa872378a2f">

It ends up like this:

<img width="500" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/69429/c721ee51-bbcc-4517-b53d-216a7861d60f">

Consider adding support for inline highlighting (maybe through a second toolbar icon?)

**Comment by gregorias** [comment]
Does pygments work for you? https://github.com/gregorias/anki-code-highlighter?tab=readme-ov-file#supported-highlighters

**Comment by slnc** [comment]
Oops, yes, thanks and sorry, I tried it before I started wanting to add inline code and then forgot that it allowed it.
