### ISSUE TITLE
Language choice

### ISSUE THREAD

**Issue by domluther** [gregorias/anki-code-highlighter#85]
I code in a few languages, but C++ is not one of them. This means each time I often have to change the language.

Two options to make this easier...
1. Default language eg javascript
2. User-defined list of languages so I could hide those ones I don't need.

The first one is surely easiest to implement and while the second one speeds things up a bit it's more complex and if I decide to learn a new language I'd need to go and add it back in.

**Comment by gregorias** [comment]
Hi, thanks for writing this up. I think it’s a good idea, but I’m short on time at this moment. I’ll get into this once my life gets less hectic.

**Comment by gregorias** [comment]
I’ve implemented wizard state persistence, which should satisfy this feature request. Let me know if you have further comments.
