### ISSUE TITLE
[New Feature] Enable ChatGPT Markdown style - including code

### ISSUE THREAD

**Issue by hienstorfer** [gregorias/anki-code-highlighter#87]
Hello,
what a lot of people might want to use is ChatGPT markdown.
At the end of a ChatGPT response, you can copy everything as markdown into the Clipboard.
This is also including code snippets in various languages.
As a first improvment, the Markdown itself would be cool to have - for all these non programmers out there.

**==Example GPT result== how to copy**
<img width="571" alt="image" src="https://github.com/gregorias/anki-code-highlighter/assets/55869471/a2b8cf36-6c88-409d-8ce7-52b1197bbc75">

**==Example GPT result==**

[python]

Tuples and sets are both built-in data types in Python, but they have different properties and use cases. Here’s a detailed comparison:

### Tuple
1. **Ordered**: Tuples maintain the order of elements. The order in which elements are added to a tuple is preserved.
2. **Immutable**: Once a tuple is created, its elements cannot be changed, added, or removed. This immutability makes tuples hashable, allowing them to be used as keys in dictionaries and elements of sets.
3. **Duplicates Allowed**: Tuples can contain duplicate elements.
4. **Indexable**: Elements in a tuple can be accessed using indices.
5. **Syntax**: Tuples are created using parentheses `()`.

### Example of a Tuple
```python
my_tuple = (1, 2, 3, 4, 2)
print(my_tuple[0])  # Output: 1
print(my_tuple)     # Output: (1, 2, 3, 4, 2)
```

### Set
1. **Unordered**: Sets do not maintain any order of elements. The order of elements is not preserved and may change.
2. **Mutable**: Sets are mutable; you can add or remove elements from a set. However, the elements themselves must be immutable.
3. **No Duplicates**: Sets do not allow duplicate elements. Each element in a set is unique.
4. **Not Indexable**: Since sets are unordered, you cannot access elements using indices.
5. **Syntax**: Sets are created using curly braces `{}` or the `set()` function.

### Example of a Set
```python
my_set = {1, 2, 3, 4, 2}
print(my_set)  # Output: {1, 2, 3, 4}
my_set.add(5)
print(my_set)  # Output: {1, 2, 3, 4, 5}
```

### Key Differences
1. **Order**: Tuples maintain order; sets do not.
2. **Mutability**: Tuples are immutable; sets are mutable.
3. **Duplicates**: Tuples allow duplicates; sets do not.
4. **Indexing**: Tuples can be indexed; sets cannot.
5. **Use Cases**: Tuples are often used for heterogeneous data (different data types) and fixed collections of items. Sets are used for membership testing, removing duplicates from a sequence, and mathematical operations like union, intersection, and difference.

Understanding these differences helps in choosing the appropriate data type based on the requirements of the task at hand.

**Comment by gregorias** [comment]
Hi Phillip,

I recently stopped my ChatGPT description. Could I ask you to provide the HTML code of an Anki field that results from such a copy?

**Comment by otrai** [comment]
This is what I get when I press the copy button:

<img width="1174" alt="image" src="https://github.com/user-attachments/assets/df9ed5b6-3e1f-4e41-8ece-bace58738101">

**Comment by otrai** [comment]
Was the above information what you needed in order to add this feature for ChatGPT?

**Comment by gregorias** [comment]
I won’t be following up on this enhancement. I don’t have enough time to implement this and later support the extended feature set.
