### ISSUE TITLE
The plugin seems to apply formatting but not highlighting.

### ISSUE THREAD

**Issue by AdrianeNS** [gregorias/anki-code-highlighter#88]
Hello,
I just installed this today by adding the number provided on Anki's add-on page.  I tried using it to format some Bash code but when I highlighted the code and then pressed on the add-on's button, it didn't fully work.  It did format the code but it did not highlight it.  I tried again using Python to see if the issue was with Bash but I got the same result.  I'm just wondering if I'm missing a step here.  Do I also need to install the supported highlighters separately?  I'm not sure what else I might be doing wrong.

**Comment by gregorias** [comment]
Hi @AdrianeNS,

No, the plugin was written to be work immediately. Just to be sure, did you check how the card renders (ctrl/cmd + L)? The styles do not apply in the note editor.

**Comment by gregorias** [comment]
See also https://github.com/gregorias/anki-code-highlighter/issues/71#issuecomment-1815164324 for screenshots of expected behavior.

**Comment by AdrianeNS** [comment]
Thanks so much for replying so quickly.  I did not realize highlighting was not applied in the editor.  I checked the cards and look like they're supposed to.  Thanks again!
